### ISSUE TITLE
semantic parsing 运行有误

### ISSUE THREAD

**Issue by zjcai96** [zhedongzheng/tensorflow-nlp#11]
您好，我最近想复用semantic parsing的代码，注意到您更新了rnn-seq2seq，但是word embedding没有更新，想请问你用的什么embedding方式。
![image](https://user-images.githubusercontent.com/45651633/57872170-afd7bb80-783d-11e9-9683-5d8a674ed07d.png)
另外我在尝试transformer的代码时遇到了不训练的问题，不知道问题出在哪里，请您指教。
![image](https://user-images.githubusercontent.com/45651633/57874583-7efa8500-7843-11e9-9e5b-74122b61b5db.png)

**Comment by zhedongzheng** [comment]
您好，

对于第一个问题，我确实忘了更新，我刚刚push了新的 make_data.ipynb，里面做了pretrained embedding，用的是 glove.840B.300d.txt，需要自行下载

对于第二个问题，由于版权和容量原因，我在GitHub上发的[数据](https://github.com/zhedongzheng/finch/blob/master/finch/tensorflow2/semantic_parsing/tree_slu/data/train.tsv)只是例子（只有20行而已），不是完整的数据。你需要去下载完整的数据，然后替换掉原来的文件。完整的数据可以用两行命令下载：
```
$ curl -o top-dataset-semantic-parsing.zip -L https://fb.me/semanticparsingdialog
$ unzip top-dataset-semantic-parsing.zip
```
