### ISSUE TITLE
use baseline_lstm_train_clr to predict and occurred an error，how to fix it

### ISSUE THREAD

**Issue by hbwzhsh** [zhedongzheng/tensorflow-nlp#12]
ValueError: Shape must be rank 2 but is rank 3 for 'Decoder/decoder/while/BeamSearchDecoderStep/tied_dense/MatMul' (op: 'MatMul') with input shapes: [?,10,300], [3853,300].

**Comment by zhedongzheng** [comment]
Hi, are you using the same code and do you have other modifications?
are you using TensorFlow version 1.15.2 or other version?
When I run my script "baseline_lstm_train_clr.ipynb", there seems no problem.

**Comment by hbwzhsh** [comment]
I am using tensorflow version 1.13.2
