### ISSUE TITLE
“cc.zh.300.vec ” where download? can you give a link? Thanks

### ISSUE THREAD

**Issue by CoderBinGe** [zhedongzheng/tensorflow-nlp#13]

**Comment by zhedongzheng** [comment]
Hi,

https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.zh.300.vec.gz

I use this link, and please don't forget to decompress the .gz file

`gzip -d cc.zh.300.vec.gz`

then you will see `cc.zh.300.vec` which is quite large (4G) but the vector quality is good

**Comment by CoderBinGe** [comment]
OK, Thank you very much!
