### ISSUE TITLE
request: more explanations on models

### ISSUE THREAD

**Issue by lixbgo** [zhedongzheng/tensorflow-nlp#6]
In this project, i can't understand some models . Do you have a simple explanation of the model?

**Comment by zhedongzheng** [comment]
Hi, Thanks for raising this issue. I am considering how to do this, the solutions may be:

1. provide the link of paper(s) associated with this model in notebook
2. provide some simple descriptions of the model in notebook

I will begin by these two points, more ideas are always welcome

**Comment by lixbgo** [comment]
Thank you for your reply，I have a suggestion： If there is no paper related to the model, I suggest you could provide some simple descriptions and an simple example of the model. This is a good way to allow one to understand what the model does.
